fav_dirs = [
    "~/Projects",
    "~/work",
    "~/.config",
    "~/brain",
]

exclude = [
    "*.git*",
    "node_modules",
    "target",
    "build",
    "dist",
    "*.tmp",
    "*.log",
    "*.cache"
]

editor = "nvim"

project_markers = [
".git", ".hg", ".svn", "Makefile", "CMakeLists.txt", "pom.xml", "build.gradle", "build.gradle.kts", 
 "Cargo.toml", "setup.py", "pyproject.toml", "requirements.txt", "Gemfile", "Mix.exs", "rebar.config", 
 "project.clj", "deps.edn", "shard.yml", "pubspec.yaml", "elm.json", "Project.toml", "dune-project", 
 "xmake.lua", "SConstruct", "meson.build", "WORKSPACE", "default.nix", "flake.nix", "TAGS", "GTAGS"
]

max_depth = 10

preview_max_size = 1048576
