name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ stable, beta ]

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2  # super-speed Rust builds :contentReference[oaicite:0]{index=0}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
